#!/usr/bin/env perl

### ==== 出力先 ====
$out_dir = 'out';

### ==== LuaLaTeX（デフォルト） ====
$lualatex = 'lualatex -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %O %S';
$pdflualatex = $lualatex;

# latexmk が使うデフォルトエンジンを LuaLaTeX に寄せたいなら
$latex = $lualatex;

# PDF 生成モード：LuaLaTeX を使う（4 が LuaLaTeX）
$pdf_mode = 4;

# 最大再コンパイル回数
$max_repeat = 5;

### ==== BibTeX / Biber ====
$bibtex = 'bibtex %O %S';
$biber  = 'biber --bblencoding=utf8 -u -U --output_safechars %O %S';

### ==== Index ====
$makeindex = 'mendex %O -o %D %S';

### ==== pLaTeX（必要な時だけ使う） ====
$platex = 'platex -synctex=1 -halt-on-error -interaction=nonstopmode -file-line-error %O %S';
# ↑ platex を直接使う場合は、コマンドラインで -latex=platex を指定

### ==== Previewer ====
$pvc_view_file_via_temporary = 0;
if ($^O eq 'linux') {
    # vimtex と相性のいい Zathura を使う
    $pdf_previewer = "zathura %S";
    $dvi_previewer = "xdg-open %S";
} elsif ($^O eq 'darwin') {
    $pdf_previewer = "open %S";
    $dvi_previewer = "open %S";
} else {
    $pdf_previewer = "start %S";
    $dvi_previewer = "start %S";
}

### ==== Clean targets ====
$clean_full_ext = "%R.synctex.gz";
