-- Plugin modules are loaded in this order so language settings extend the shared defaults.
return {
  { import = "plugins.core" },
  { import = "plugins.coding" },
  { import = "plugins.colorscheme" },
  { import = "plugins.editor" },
  { import = "plugins.formatting" },
  { import = "plugins.linting" },
  { import = "plugins.lsp" },
  { import = "plugins.treesitter" },
  { import = "plugins.ui" },
  { import = "plugins.util" },
  { import = "plugins.blink" },
  { import = "plugins.lang.typescript" },
  { import = "plugins.snacks_explorer" },
  { import = "plugins.snacks_picker" },
  { import = "plugins.dial" },
  { import = "plugins.inc_rename" },
  { import = "plugins.lang.clangd" },
  { import = "plugins.lang.go" },
  { import = "plugins.lang.json" },
  { import = "plugins.lang.markdown" },
  { import = "plugins.lang.python" },
  { import = "plugins.lang.tex" },
  { import = "plugins.dot" },
  { import = "plugins.mini_hipatterns" },
}
