format = """
[░▒▓](#a3aed2)\
[  ](bg:#a3aed2 fg:#090c0c)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$nodejs\
$rust\
$golang\
$php\
$python\
$java\
$docker_context\
$c\
[](fg:#212736 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

command_timeout = 1000

# ─── Character ───────────────────────────────
[character]
success_symbol = "[❯](bold fg:#98be65)"
error_symbol   = "[❯](bold fg:#ff6c6b)"

# ─── Directory ───────────────────────────────
[directory]
style = "fg:#e3e5e5 bg:#769ff0"
format = "[ $path]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music"     = " "
"Pictures"  = " "

# ─── Git ─────────────────────────────────────
[git_branch]
symbol = ""
style  = "fg:#769ff0 bg:#394260"
format = "[ $symbol $branch]($style)"

[git_status]
style  = "fg:#769ff0 bg:#394260"
format = "[ $all_status$ahead_behind]($style)"

# ─── Languages ───────────────────────────────
[nodejs]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[rust]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[golang]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[php]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[python]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[java]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

[docker_context]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($context) ](fg:#769ff0 bg:#212736)]($style)'

[c]
symbol = ""
style  = "fg:#769ff0 bg:#212736"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#212736)]($style)'

# ─── Time ────────────────────────────────────
[time]
disabled    = false
time_format = "%R"
style       = "fg:#a0a9cb bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
